FROM php:7.3.6-fpm-alpine3.9

RUN apk add mysql-client openssl \
    && docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www/html

WORKDIR /var/www/html

RUN composer install && \
    php artisan config:cache && \
    chmod -R 777 storage

# RUN ln -s public .

EXPOSE 9000

ENTRYPOINT ["php-fpm"]
